CREATE TABLE "TRANSPORTATION"."USER_DATA" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 CHAR) UNIQUE, 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR) UNIQUE, 
	 PRIMARY KEY ("ID"));

CREATE SEQUENCE user_data_seq
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1;
  